### PR TITLE
feat: add composition-api support

### PR DESCRIPTION
**Pull request by FRSgit**
Hi, thank you for the awesome library! In this PR I've added missing support for the composition-api.

Without these changes I was getting the `TypeError: Cannot read property 'meta' of undefined` error every time.
You can reproduce the problem by reverting the changes I did to `src/index.js` and running the test case I've created.

I'm not sure about the code style within `index.js` - it's definitely not my style of writing js, so if you have any suggestion regarding that - feel free to suggest changes 😄 

If you have any questions - I'm ready to answer them ;)

### CODE REVIEW

**Comment by FRSgit** [comment]
Btw. before I started this PR there were few lines that was missing the coverage and after my changes number of uncovered lines stayed the same, so I'd say in this regard should be OK

**Comment by dword-design** [comment]
@FRSgit LGTM so far, very nice! I was thinking, do we also need the composition API for non-TypeScript components?

**Comment by FRSgit** [comment]
@dword-design Yes, we need it as well, I'll add it. `index.js` line 108, right?

**Comment by FRSgit** [comment]
@dword-design Done!

**Comment by dword-design** [comment]
Great thanks for implementing!

**Comment by FRSgit** [comment]
@dword-design Sure, thanks for merging it up so quick!

**Pull request merged**
