### PR TITLE
Fix error when "meta" is not declared in the page

### PR DESCRIPTION
**Pull request by MatHackDev**

### CODE REVIEW

**Comment by dword-design** [comment]
@MatHackDev Thanks for contributing and sorry for the late response! I think we need a test for this that failed and is fixed by the change. In the current tests there are some without the meta field and it works. How does the page look like that leads to the error and how are you using the module?

**Review by Mikaleb — APPROVED** [review]

**Comment by mvandiest** [comment]
FYI, I get the same issue when building against a boilerplate Nuxt app. Not sure why the current tests don't fail for this. Guessing it's something related to nuxt TypeScript strictness. But just a guess without having looked at the existing tests.

**Comment by JorgesOS7** [comment]
> FYI, I get the same issue when building against a boilerplate Nuxt app. Not sure why the current tests don't fail for this. Guessing it's something related to nuxt TypeScript strictness. But just a guess without having looked at the existing tests.
> 
> ```
> $ nuxt
> 
>    ╭───────────────────────────────────────╮
>    │                                       │
>    │   Nuxt @ v2.15.8                      │
>    │                                       │
>    │   ▸ Environment: development          │
>    │   ▸ Rendering:   server-side          │
>    │   ▸ Target:      server               │
>    │                                       │
>    │   Listening: http://localhost:3000/   │
>    │                                       │
>    ╰───────────────────────────────────────╯
> 
> ℹ Preparing project for development                                                                                                                12:00:57
> ℹ Initial build may take a while                                                                                                                   12:00:57
> ✔ Builder initialized                                                                                                                              12:00:57
> 
>  ERROR  Cannot read property 'meta' of undefined                                                                                                   12:00:57
> 
>   at extractMeta (node_modules/nuxt-route-meta/dist/index.js:141:15)
>   at Object.parseRoutes (node_modules/nuxt-route-meta/dist/index.js:149:57)
>   at next (node_modules/@nuxt/utils/dist/utils.js:659:27)
>   at Object.extendRoutes (node_modules/@nuxt/utils/dist/utils.js:674:12)
>   at Builder.resolveRoutes (node_modules/@nuxt/builder/dist/builder.js:546:56)
>   at async Promise.all (index 1)
>   at async Builder.generateRoutesAndFiles (node_modules/@nuxt/builder/dist/builder.js:375:5)
>   at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:319:5)
>   at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:107:5)
>   at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:65:7)
> ```
> 
> Even after adding meta to all pages my build still failed as I'm using `@nuxtjs/svg-sprite` package and it adds an `_icons` page dynamically of which I have no control of to be able to add meta prop.
> 
> If I locally update the offending line in `node_modules` to null check as this PR does, the project builds fine.
> 
> ```
> return { ...(_data = data, (0, _omit.default)(['meta', ...(_predefinedProperties = predefinedProperties, (0, _keys.default)(_predefinedProperties))])(_data)),
>       ...data?.meta
>     };
> ```

I have the same error, any solution for that?

**Comment by dword-design** [comment]
It should be fixed. Lock file update reproduced the issue

**Pull request closed without merging**
